[commgestion]
    debug = true
    # SECURITY WARNING: keep the secret key used in production secret!
    secret_key = "__Insecure Dev Key__"
    allowed_hosts = ["localhost", "127.0.0.1"]

    [commgestion.db]
        kind = "sqlite3"
        path = "db.sqlite3"
